/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SellRouteImport } from './routes/sell'
import { Route as AccessoriesRouteImport } from './routes/accessories'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'

const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessoriesRoute = AccessoriesRouteImport.update({
  id: '/accessories',
  path: '/accessories',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessories': typeof AccessoriesRoute
  '/sell': typeof SellRoute
  '/category/$slug': typeof CategorySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessories': typeof AccessoriesRoute
  '/sell': typeof SellRoute
  '/category/$slug': typeof CategorySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accessories': typeof AccessoriesRoute
  '/sell': typeof SellRoute
  '/category/$slug': typeof CategorySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/accessories' | '/sell' | '/category/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/accessories' | '/sell' | '/category/$slug'
  id: '__root__' | '/' | '/accessories' | '/sell' | '/category/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessoriesRoute: typeof AccessoriesRoute
  SellRoute: typeof SellRoute
  CategorySlugRoute: typeof CategorySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessories': {
      id: '/accessories'
      path: '/accessories'
      fullPath: '/accessories'
      preLoaderRoute: typeof AccessoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessoriesRoute: AccessoriesRoute,
  SellRoute: SellRoute,
  CategorySlugRoute: CategorySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
